[package]
name = "bevy-mesh-text-3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16.0", default-features = false, features = [
	"bevy_asset",
	"bevy_log",
	"bevy_render",
] }
cosmic-text = "0.14.2"
lyon = "1.0.1"
thiserror = "2.0.12"
